[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["H3rmt"]
license = ""
repository = ""
default-run = "app"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0", features = [] }

[workspace]
members = [".", "entity", "migrations"]

[dependencies]
serde_json = "1.0.85"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0", features = ["fs-write-file", "path-all"] }
dirs = "4.0.0"
tokio = { version = "1.21.0", features = ["full"] }
sea-orm = { version = "0.9.2", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros", "debug-print"] }
ts-rs = "6.1"
toml = "0.5.9"

entity = { path = "entity" }
migration = { path = "migrations" }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
