[package]
name = "grades"
version = "0.0.1" # irrelevant (tauri.conf.json will override)
description = "tauri app to manage grades in school"
authors = ["H3rmt"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
license = "MIT"
repository = "https://github.com/H3rmt/grades/"

[build-dependencies]
tauri-build = { version = "1.2.0", features = [] }
built = { version = "0.5.1", features = ["git2"] }

[workspace]
members = [".", "entity", "migrations"]

[dependencies]
serde_json = "1.0.87"
serde = { version = "1.0.147", features = ["derive"] }
tauri = { version = "1.2.0", features = ["fs-write-file", "path-all", "updater"] }
dirs = "4.0.0"
tokio = { version = "1.21.2", features = ["full"] }
sea-orm = { version = "0.10.2", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros", "debug-print"] }
ts-rs = "6.2.1"
toml = "0.5.9"
error-stack = "0.2.4"
log = "0.4.17"
env_logger = "0.9.0"


entity = { path = "entity" }
migration = { path = "migrations" }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
strip = "debuginfo"
lto = true
