[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migrations"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
sea-orm-migration = { version = "0.9.3", features = ["sqlx-sqlite", "runtime-tokio-native-tls"] }