[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migrations"
path = "src/lib.rs"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }

[dependencies.sea-orm-migration]
version = "0.9.2"
features = [
	"sqlx-sqlite",
	"runtime-async-std-native-tls",
]
