// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Model { id: number, subject: number, type: number, info: string, grade: number, period: number, not_final: boolean, confirmed: string | null, date: string, weight: 'Default' | 'Double' | 'Half', }