// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Info { version: string, name: string, authors: string, target: string, profile: string, build_on: string, build_time: string, repository: string, commit_hash_short: string, }