//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub use super::grade_types::{ActiveModel as ActiveGradeType, Entity as GradeTypes, Model as GradeType};
pub use super::grades::{ActiveModel as ActiveGrade, Entity as Grades, Model as Grade};
pub use super::periods::{ActiveModel as ActivePeriod, Entity as Periods, Model as Period};
pub use super::subjects::{ActiveModel as ActiveSubject, Entity as Subjects, Model as Subject};

