//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub use super::grade_types::Entity as GradeTypes;
pub use super::grades::Entity as Grades;
pub use super::periods::Entity as Periods;
pub use super::subjects::Entity as Subjects;
