//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub use super::grade_types::{ActiveModel as ActiveGradeType, Column as GradeTypeColumn, Entity as GradeTypes, Model as GradeType, Relation as GradeTypeRelation};
pub use super::grades::{ActiveModel as ActiveGrade, Column as GradeColumn, Entity as Grades, Model as Grade, Relation as GradeRelation};
pub use super::periods::{ActiveModel as ActivePeriod, Column as PeriodColumn, Entity as Periods, Model as Period, Relation as PeriodRelation};
pub use super::subjects::{ActiveModel as ActiveSubject, Column as SubjectColumn, Entity as Subjects, Model as Subject, Relation as SubjectRelation};

