// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GradeModalDefaults { grade_default: number, subject_default: string, type_default: string, period_default: string, info_default: string, not_final_default: boolean, double_default: boolean, }