[package]
name = "entity"
version = "0.11.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/mod.rs"

[dependencies]
serde = { version = "1.0.147", features = ["derive"] }
sea-orm = "0.10.2"
ts-rs = "6.2.1"