// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `subjects` table.
    ///
    /// (Automatically generated by Diesel.)
    subjects (id) {
        /// The `id` column of the `subjects` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `subjects` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `color` column of the `subjects` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        color -> Text,
    }
}

diesel::table! {
    /// Representation of the `types` table.
    ///
    /// (Automatically generated by Diesel.)
    types (id) {
        /// The `id` column of the `types` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `types` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `color` column of the `types` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        color -> Text,
    }
}

diesel::allow_tables_to_appear_in_same_query!(
    subjects,
    types,
);
