name: "check"

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tauri:
    name: check-rust
    runs-on: ubuntu-20.04
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          prefix-key: rust-ubuntu-20.04
      - name: Run tests
        run: cd src-tauri && cargo test --verbose

  js:
    name: check-js
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: install app dependencies
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn run build
      - name: test
        run: yarn run test

  actions:
    name: check-js-actions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: ./workflows/yarn.lock
          node-version: 16
          cache: 'yarn'
      - run: yarn --cwd ./workflows install --frozen-lockfile
      - run: yarn --cwd ./workflows run check
      - run: yarn --cwd ./workflows run dist