name: "check-version-release"

on:
  pull_request:
    branches:
      - release

jobs:
  check:
    name: check-version-release
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: ./workflows/yarn.lock
          node-version: 16
          cache: 'yarn'
      - run: yarn --cwd ./workflows install --frozen-lockfile
      - run: yarn --cwd ./workflows run dist
      - name: get Version
        id: get-version
        uses: SebRollen/toml-action@v1.0.2
        with:
          file: 'src-tauri/Cargo.toml'
          field: "package.version"
      - name: get latest release version
        id: check-latest-release-version
        uses: actions/github-script@v6
        with:
          retries: 3
          script: |
            const script = require('./workflows/src/check-version-release-check-latest-release-version.js')
            return await script.default({github, context, core})

      - name: check new version is greater that older
        run: |
          Old="${{ steps.check-latest-release-version.outputs.result }}"
          New="${{ steps.get-version.outputs.value }}"
          echo "latest release version: $Old"
          echo "new version: $New"
          arrVersionOld=(${Old//./ })
          arrVersionNew=(${New//./ })
          if [[ ${arrVersionOld[0]} -lt ${arrVersionNew[0]} || ${arrVersionOld[1]} -lt ${arrVersionNew[1]} || ${arrVersionOld[2]} -lt ${arrVersionNew[2]} ]]; then
            echo "New Version $New is newer than $Old"
            exit 0
          else
            echo "New Version $New is not newer than $Old"
            exit 1
          fi

