name: "publish release"

on:
  push:
    branches:
      - release

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}
      version: ${{ steps.get-version.outputs.prop }}

    steps:
      - uses: actions/checkout@v3
      - name: Get Version
        id: get-version
        uses: SebRollen/toml-action@v1.0.2
        with:
          file: 'src-tauri/Cargo.toml'
          field: "package.version"
      - name: create release
        id: create-release
        uses: actions/github-script@v6
        with:
          retries: 3
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `grades-app-v${{ steps.get-version.outputs.prop }}`,
              name: `grades v${{ steps.get-version.outputs.prop }}`,
              body: 'Assets getting generated...',
              draft: true,
              prerelease: false
            })

            core.notice(`created release: grades v${{ steps.get-version.outputs.prop }}`)

            return data.id

  tauri:
    name: build tauri
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-20.04, windows-latest ]
    runs-on: ${{ matrix.platform }}
    env:
      CARGO_TERM_COLOR: always
    outputs:
      winupdate: ${{ steps.build.outputs.winupdate }}
      macupdate: ${{ steps.build.outputs.macupdate }}
      linupdate: ${{ steps.build.outputs.linupdate }}
      winsig: ${{ steps.build.outputs.winsig }}
      macsig: ${{ steps.build.outputs.macsig }}
      linsig: ${{ steps.build.outputs.linsig }}

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - uses: h3rmt/tauri-action@v0.2.0
        id: build
        env:
          TOKEN: ${{ secrets.PAT }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          version: ${{ needs.create-release.outputs.version }}
          name: grades

  publish-release:
    runs-on: ubuntu-latest
    needs: [ tauri, create-release ]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v6
        with:
          retries: 3
          script: |
            const { data } = await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ needs.create-release.outputs.release_id }},
              body: 'Take a look at the assets to download and install this app.',
              draft: false,
              prerelease: false
            })

            core.notice(`published release`);

  update-update-json:
    runs-on: ubuntu-latest
    needs: [ publish-release, tauri, create-release ]

    steps:
      - name: update-update-json
        uses: h3rmt/tauri-action@v0.2.0
        env:
          TOKEN: ${{ secrets.PAT }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          version: ${{ needs.create-release.outputs.version }}
          gistId: 9f0a67b7ad425e9fb74b32f6afcab111
          releaseNotes: ${{ github.event.head_commit.message }}
          releaseTagName: grades-app-v${{ needs.create-release.outputs.version }}

          winsig: ${{ needs.tauri.outputs.winsig }}
          macsig: ${{ needs.tauri.outputs.macsig }}
          linsig: ${{ needs.tauri.outputs.linsig }}
          winupdate: ${{ needs.tauri.outputs.winupdate }}
          macupdate: ${{ needs.tauri.outputs.macupdate }}
          linupdate: ${{ needs.tauri.outputs.linupdate }}
